#!/bin/ash

PATH="/bin:/usr/bin"
export PATH

n=0
if [ $(/usr/share/bytespeicher/connected_devices) -eq 0 ]
then
        open="false"
        connected_string="No devices connected"
else
        open="true"
        if [ $(/usr/share/bytespeicher/connected_devices) -eq 1 ]
        then
                connected_string="1 device connected"
        else
                connected_string="$(/usr/share/bytespeicher/connected_devices) devices connected"
        fi
fi

onlineusercount=$(/usr/share/bytespeicher/connected_users | sed -n 1p)
if [ ! -z $onlineusercount ] && [ $onlineusercount -gt 0 ]
then
        onlineuserlist=",\"names\": ["$(/usr/share/bytespeicher/connected_users | sed -n 2p)"]"
fi

lastchange=$(/usr/share/bytespeicher/connected_devices --last-change)

cat <<EOL
{
        "state": {
                "open": $open,
                "lastchange": $lastchange,
                "message": "$connected_string"
        },
        "status": "$connected_string",
        "open": $open,
        "sensors": {
                "people_now_present": [
                {
                        "value": ${onlineusercount:-0}
                        $onlineuserlist
                }
                ]
        }
}
EOL


